osx_image: xcode8
language: objective-c

script:
- xcodebuild clean build -project Sugar.xcodeproj -scheme Sugar-iOS -sdk iphonesimulator
- xcodebuild test -project Sugar.xcodeproj -scheme Sugar-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
- xcodebuild clean build -project Sugar.xcodeproj -scheme Sugar-Mac -sdk macosx
- xcodebuild test -project Sugar.xcodeproj -scheme Sugar-Mac -sdk macosx
- xcodebuild clean build -project Sugar.xcodeproj -scheme Sugar-tvOS -sdk appletvsimulator
- xcodebuild test -project Sugar.xcodeproj -scheme Sugar-tvOS -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0'

notifications:
  email: false
